FROM node:20


#This apply AFTER INIT project
WORKDIR /backend
COPY . .

# This only to INIT project
# RUN npm install -g @nestjs/cli 
# RUN nest new . --skip-install --package-manager npm 

RUN npm install